name: client instance CD

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: |
          cd /home/ubuntu/frontend
          git fetch --all
          git reset --hard origin/dev
          git pull origin dev
          npm run build
